### ISSUE TITLE
Support for Adafruit Feather RP2040?

### ISSUE THREAD

**Issue by muralivnv** [majbthrd/pico-debug#11]
I followed the exact steps detailed under *howto* folder and after copying *pico-debug-gimmecache.uf2*, Feather RP2040 does not boot as an CMSIS adapter. It seems the uf2 need to be built with Feather RP2040 with different config.

**Comment by majbthrd** [comment]
I suspect that there is a far more mundane explanation rather that the Feather RP2040 being any different.

When you say "does not boot as an CMSIS adapter", what does this phrase mean to you?

Here's how I would define it.  After copying over the .uf2 to the RP2040, the RP2040 reboots.  At this point...

If in Linux, you should be able to issue the command:

`
lsusb
`

and see something like the following in its output:

`
Bus 001 Device 005: ID 1209:2488 InterBiometrics
`

Note that due to the near infinite number of Linux variations, instead of "InterBiometrics", you may see something different, but the "1209:2488" will be the same.

If in Windows, go to the Device Manager, and under "Human Interface Devices", look for a "HID-compliant vendor-defined device" whose properties have a "Details" tab with HID\VID_1209&PID_2488.  Here's a sample screenshot.

![111808455-0252ea80-88a2-11eb-9da8-196eae365b00](https://user-images.githubusercontent.com/12226419/119238536-7ad76100-bb08-11eb-8dd6-86597bcac192.png)

For Mac, I think there may be a "lsusb" equivalent like the Linux explanation, but I don't use Mac.

If the above tests pass, it is already booting as a CMSIS-DAP adapter.

Now, if you are using Linux, perhaps you haven't installing a udev rule with a rule for 1209:2488?  That would mean the device is available, but only to root.

Beyond that, it is almost certainly user error or user mis-configuration.
